version: "3.7"

services:

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    volumes:
      - .:/var/www/laravel-api-test
      - ./nginx/laravel-api-test.conf:/etc/nginx/conf.d/laravel-api-test.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - laravel
      - postgres
    ports:
      - 80:80
    networks:
      - network

  laravel:
    working_dir: /var/www/laravel-api-test/laravel
    build:
      context: .
      dockerfile: laravel/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./laravel:/var/www/laravel-api-test/laravel
      - ./laravel/back.sh:/back.sh
    environment:
      XDEBUG_SESSION: 1
      PHP_IDE_CONFIG: serverName=laravel-api-test
    networks:
      - network
    entrypoint: /back.sh
    tty: true

  postgres:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=laravel-api-test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - box-postgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - network

volumes:
  box-postgres:
networks:
  network:
