GET http://laravel-api-test.local/api/teachers

###
GET http://laravel-api-test.local/api/students

###
GET http://laravel-api-test.local/api/assessment

###
GET http://laravel-api-test.local/api/students/1

###
POST http://laravel-api-test.local/api/students_to_assessments
Content-Type: application/json

{
  "id_teacher" : "1",
  "id_student" : "1",
  "id_assessment" : "1"
}
###
POST http://laravel-api-test.local/api/students_to_assessments/stores
Content-Type: application/json

{
  "id_teacher" : "1",
  "assessments" : [
    {"id_student" : "1", "id_assessment" : "1"},
    {"id_student" : "2", "id_assessment" : "2"}
  ]
}
###



